version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - my-network
  app:
    container_name: rest-api-ts-app
    build: .
    env_file: .env
    ports:
      - 3000:3000
    networks:
      - my-network

networks:
  my-network:
    driver: bridge